# Generated by Django 3.2.16 on 2024-11-14 09:17

import apps.curiosidades.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.curiosidades.models.curiosidad_imagen_directorio)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
