# Generated by Django 3.2.16 on 2024-12-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('experiencia_mascotas', models.BooleanField()),
                ('espacio_suficiente', models.BooleanField()),
                ('motivo_adopcion', models.TextField()),
                ('tipo_mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=50)),
                ('identificacion_oficial', models.FileField(upload_to='documentos/')),
                ('comprobante_domicilio', models.FileField(upload_to='documentos/')),
                ('acepto_terminos', models.BooleanField()),
                ('confirmo_veracidad', models.BooleanField()),
            ],
        ),
    ]
