# Generated by Django 3.2.16 on 2024-11-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('experiencia_con_mascotas', models.BooleanField()),
                ('espacio_suficiente', models.BooleanField()),
                ('motivo_adopcion', models.TextField()),
                ('tipo_mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=50)),
                ('identificacion_oficial', models.FileField(upload_to='documentos/identificacion/')),
                ('comprobante_domicilio', models.FileField(upload_to='documentos/domicilio/')),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('confirmacion', models.BooleanField(default=False)),
            ],
        ),
    ]
