# Generated by Django 3.2.16 on 2024-11-14 09:13

import apps.mascotas.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('foto', models.ImageField(max_length=500, upload_to=apps.mascotas.models.mascota_foto_directorio)),
                ('descripcion', models.TextField(max_length=255)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('color', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('vistas', models.IntegerField(blank=True, default=0)),
                ('publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('registro_veterinario', models.FileField(blank=True, null=True, upload_to=apps.mascotas.models.registro_veterinario_directorio)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
            ],
            options={
                'ordering': ('publicacion',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('mascotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteo_vistas_mascotas', to='mascotas.mascotas')),
            ],
        ),
    ]
