# Generated by Django 5.1.3 on 2024-12-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascotas_actividad_mascotas_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='niños',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='tiempo_cuidado',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='vivienda',
        ),
    ]
